### ISSUE TITLE
Issue training a custom model

### ISSUE THREAD

**Issue by ariane-lozachmeur** [mskcc/mimsi#15]
Hi! 

First of all thank you for developing and sharing this tool. It is very easy to use a yields very good results. 

I am trying to train my own model using the command line you suggest in your README.
Once training is over I hit this error:
```Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/mimsi/main/mi_msi_train_test.py", line 275, in <module>
    main()
  File "/home/ubuntu/mimsi/main/mi_msi_train_test.py", line 60, in main
    generate_model(seed, cuda, epochs, lr, reg, train_location, test_location, save, name)
  File "/home/ubuntu/mimsi/main/mi_msi_train_test.py", line 267, in generate_model
    final_loss, final_err = test(test_loader, model, cuda)
TypeError: test() missing 2 required positional arguments: 'save' and 'name'
```

I took a look at the code and it seems like adding the `save` and `name` arguments to the `test` function at line 267 solves the issue: ie in `mi_msi_train_test.py` line 267:
```final_loss, final_err = test(test_loader, model, cuda)```
becomes
```final_loss, final_err = test(test_loader, model, cuda, save, name)```

Does that seem reasonable or am I missing something?
Thank you for you help!

**Comment by john-ziegler** [comment]
Glad you're finding MiMSI useful! Thanks for the feedback and good catch - I've added in a fix to address the missing args in that last test call.
